name: news_app
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  
  http:
  cached_network_image: ^3.2.1
  path_provider:
  auto_size_text: ^3.0.0
  getwidget:
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 
  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/loading.gif
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
